spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/springcloudtest?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9078
  servlet:
    context-path: /testAll
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath:/mapper/*.xml




